### ISSUE TITLE
You must call and await the initialize function before attempting to call any other MSAL API

### ISSUE THREAD

**Issue by alexdev888** [MazenSenih/MsalWithNextJs14#2]
When I make a change to the code and HMR triggers an update I get this error in console log:

```
Error acquiring token: BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors
    at createBrowserAuthError (BrowserAuthError.mjs:274:12)
    at blockAPICallsBeforeInitialize (BrowserUtils.mjs:140:98)
    at preflightCheck (BrowserUtils.mjs:155:5)
    at preflightCheck (StandardController.mjs:80:80)
    at StandardController.acquireTokenPopup (StandardController.mjs:405:13)
    at PublicClientApplication.acquireTokenPopup (PublicClientApplication.mjs:76:32)
    at acquireAccessToken (tokenFetcher.ts:36:47)
    at async getCurrentToken (tokenFetcher.ts:48:13)
    at async getToken (msal.ts:29:21)
    at async fetchToken (page.tsx:11:7)
```

It looks like at this point the client is not initialised anymore and what I have to do to make my changes work is to always refresh the page after making any change.

Any ideas regarding this?

**Comment by MazenSenih** [comment]
Hi @alexdev888 , sorry for my late response,

You need to initialize it first, check the provider code, if you are not using that msal provider you can initialize it directly using the same code.
Let me know if you still need help.
